### ISSUE TITLE
allow a single file template config for user defined templates 

### ISSUE THREAD

**Issue by devkabiir** [devkabiir/scaffold#5]
This is to allow users to mix and match multiple templates and overriding of context vars in a single file

For instance a template config may contains list of other templates it depends on in the order of expansion and it may also contain variables that should be overwritten in context.

Other files in the same folder as `template.yaml` will also be used as templates and override any  file with same path/name as if dependencies

e. g. `template.yaml` 

```yaml
name: my_awesome_template
... 
...

# whether this is a template or a generator config 
# no need to specify for templates, by default its considered a template config (black value or not even specifying the key) 
type:


# whether to ignore gitingore files from expanding to output directory or to include in template generation
use_gitignore: true

# method to use for conflict resolution among templates, choice from override, ask, skip
conflict: override 

# in the order they should be expanded
dependencies:
  <name>: <optional-local-path/pub-package-name/git-url>

# variable overrides 
context:  
  var1: false

```
