### ISSUE TITLE
Allow templates to register themselves as custom command 

### ISSUE THREAD

**Issue by devkabiir** [devkabiir/scaffold#8]
In `template.yaml`
```yaml
command:  
  name: command-name
  args: <list-of-context-variables>

```
